# Generated by Django 3.2.3 on 2021-05-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=123)),
                ('relationship', models.CharField(max_length=123)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=123)),
                ('adress', models.CharField(max_length=123)),
            ],
        ),
    ]
